// Define an object to store the diet plan
const dietPlan = {
  monday: {
    eggs: 6,
    toast: 2,
    avocado: 2,
    apple: 6,
    peanutButter: 2,
    chickenBreast: 4,
    mixedVegetables: 6,
    brownRice: 2,
    greekYogurt: 6,
    mixedBerries: 3,
    salmonFillet: 4,
    sweetPotato: 2,
    wheyProteinPowder: 0.5,
    almondMilk: 4,
  },
  tuesday: {
    oatmeal: 2,
    proteinPowder: 1,
    banana: 6,
    orange: 6,
    mixedNuts: 2,
    chickenBreast: 4,
    mixedVegetables: 6,
    quinoa: 2,
    cottageCheese: 6,
    pineapple: 3,
    flankSteak: 4,
    brownRice: 2,
    mixedBerries: 3,
    almondButter: 2,
  },
  wednesday: {
    greekYogurt: 6,
    mixedBerries: 3,
    granola: 2,
    pear: 6,
    almondButter: 2,
    chickenBreast: 4,
    mixedVegetables: 6,
    quinoa: 2,
    greekYogurt: 6,
    mixedBerries: 3,
    shrimp: 4,
    brownRice: 2,
    wheyProteinPowder: 0.5,
    almondMilk: 4,
  },
  thursday: {
    toast: 2,
    almondButter: 2,
    banana: 6,
    apple: 6,
    hardBoiledEggs: 6,
    chickenBreast: 4,
    mixedVegetables: 6,
    quinoa: 2,
    cottageCheese: 6,
    mixedBerries: 3,
    salmonFillet: 4,
    sweetPotato: 2,
    mixedBerries: 3,
    peanutButter: 2,
  },
  friday: {
    eggs: 6,
    toast: 2,
    avocado: 2,
    apple: 6,
    peanutButter: 2,
    chickenBreast: 4,
    mixedVegetables: 6,
    quinoa: 2,
    greekYogurt: 6,
    mixedBerries: 3,
    flankSteak: 4,
    brownRice: 2,
    mixedBerries: 3,
    almondButter: 2,
  },
  saturday: {
    oatmeal: 2,
    proteinPowder: 1,
    banana: 6,
    apple: 6,
    peanutButter: 2,
    chickenBreast: 4,
    mixedVegetables: 6,
    quinoa: 2,
    cottageCheese: 6,
    pineapple: 3,
    shrimp: 4,
    brownRice: 2,
    wheyProteinPowder: 0.5,
    almondMilk: 4,
  },
  sunday: {
    greekYogurt: 6,
    mixedBerries: 3,
    granola: 2,
    pear: 6,
    almondButter: 2,
    chickenBreast: 4,
    mixedVegetables: 6,
    quinoa: 2,
    greekYogurt: 6,
    mixedBerries: 3,
    salmonFillet: 4,
    sweetPotato: 2,
    mixedBerries: 3,
    peanutButter: 2,
  },
};

// Calculate the total ounces per week for Person 1
const totalOunces = {
  eggs: dietPlan.monday.eggs * 3 + dietPlan.friday.eggs * 3,
  toast: dietPlan.monday.toast * 2 + dietPlan.thursday.toast * 2,
  avocado: dietPlan.monday.avocado * 2 + dietPlan.friday.avocado * 2,
  apple: dietPlan.monday.apple * 4 + dietPlan.thursday.apple * 2 + dietPlan.friday.apple * 4 + dietPlan.saturday.apple * 4,
  peanutButter: dietPlan.monday.peanutButter * 4 + dietPlan.friday.peanutButter * 2 + dietPlan.saturday.peanutButter * 2,
  chickenBreast: dietPlan.monday.chickenBreast * 3 + dietPlan.tuesday.chickenBreast * 3 + dietPlan.wednesday.chickenBreast * 3 + dietPlan.thursday.chickenBreast * 3 + dietPlan.friday.chickenBreast * 3 + dietPlan.saturday.chickenBreast * 3 + dietPlan.sunday.chickenBreast * 3,
  mixedVegetables: dietPlan.monday.mixedVegetables * 14 + dietPlan.tuesday.mixedVegetables * 14 + dietPlan.wednesday.mixedVegetables * 14 + dietPlan.thursday.mixedVegetables * 14 + dietPlan.friday.mixedVegetables * 14 + dietPlan.saturday.mixedVegetables * 14 + dietPlan.sunday.mixedVegetables * 14,
  brownRice: dietPlan.monday.brownRice * 2 + dietPlan.tuesday.brownRice * 2 + dietPlan.friday.brownRice * 2 + dietPlan.saturday.brownRice * 2,
  quinoa: dietPlan.tuesday.quinoa * 2 + dietPlan.wednesday.quinoa * 2 + dietPlan.thursday.quinoa * 2 + dietPlan.friday.quinoa * 2 + dietPlan.saturday.quinoa * 2 + dietPlan.sunday.quinoa * 2,
  greekYogurt: dietPlan.monday.greekYogurt * 7 + dietPlan.tuesday.cottageCheese * 7 + dietPlan.wednesday.greekYogurt * 7 + dietPlan.thursday.cottageCheese * 7 + dietPlan.friday.greekYogurt * 7 + dietPlan.saturday.cottageCheese * 7 + dietPlan.sunday.greekYogurt * 7,
  mixedBerries: dietPlan.monday.mixedBerries * 3 + dietPlan.tuesday.mixedBerries * 3.5 + dietPlan.wednesday.mixedBerries * 3 + dietPlan.thursday.mixedBerries * 3 + dietPlan.friday.mixedBerries * 3 + dietPlan.saturday.pineapple * 3 + dietPlan.sunday.mixedBerries * 3,
  salmonFillet: dietPlan.monday.salmonFillet * 3 + dietPlan.thursday.salmonFillet * 4 + dietPlan.sunday.salmonFillet * 4,
  sweetPotato: dietPlan.monday.sweetPotato * 2 + dietPlan.thursday.sweetPotato * 2 + dietPlan.sunday.sweetPotato * 2,
  wheyProteinPowder: dietPlan.monday.wheyProteinPowder * 12 + dietPlan.wednesday.wheyProteinPowder * 12 + dietPlan.saturday.wheyProteinPowder * 12,
  almondMilk: dietPlan.monday.almondMilk * 6 + dietPlan.wednesday.almondMilk * 4 + dietPlan.saturday.almondMilk * 4,
};

// Display the total ounces per week for Person 1
alert(totalOunces);
